# Generated by Django 3.0 on 2019-12-15 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disclaimers',
            name='en',
        ),
        migrations.RemoveField(
            model_name='disclaimers',
            name='es',
        ),
        migrations.RemoveField(
            model_name='disclaimers',
            name='fr',
        ),
        migrations.RemoveField(
            model_name='disclaimers',
            name='it',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='en',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='es',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='fr',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='it',
        ),
        migrations.AddField(
            model_name='disclaimers',
            name='language',
            field=models.ForeignKey(default='nn', on_delete=django.db.models.deletion.CASCADE, to='main.Languages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menus',
            name='language',
            field=models.ForeignKey(default='nn', on_delete=django.db.models.deletion.CASCADE, to='main.Languages'),
            preserve_default=False,
        ),
    ]
