# Generated by Django 3.0 on 2019-12-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191215_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='urlpath',
            field=models.CharField(default='nn', max_length=15),
            preserve_default=False,
        ),
    ]
