# Generated by Django 3.0 on 2019-12-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menus_urlpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menus',
            name='menu',
            field=models.CharField(max_length=15),
        ),
    ]
